services:
  postgres:
    image: postgres:13.3
    container_name: postgres-lab3
    environment:
      POSTGRES_DB: "apidemo-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"
    volumes:
      - .:/var/lib/postgresql/data
    restart: always

  keydb:
    image: "eqalpha/keydb:x86_64_v5.3.3"
    container_name: keydb-lab3
    command: "keydb-server /etc/keydb/redis.conf --server-threads 2"
    volumes:
      #      - "./redis.conf:/etc/keydb/redis.conf"
      - "data:/data"
    ports:
      - "6379:6379"
    restart: unless-stopped

  user-service:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apidemo-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: keydb
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - postgres
      - keydb
    restart: on-failure

volumes:
  data:
    driver: local
  maven_cache:
    driver: local